<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="adress.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\login\forget.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\login\login.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\login\register.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\login\style.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\login\image\bg.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\login\image\logo.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\Images\logo_steam.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\Images\new_login_bg_strong_mask.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\Images\QR.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\login.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\steam\styles.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
